version: '3.7'
services:
  # Application Container
  app:
    container_name: app
    hostname: app
    build:
      context: ./app/${USE_APP_CONTAINER}
      args:
        - TZ=${TZ}
    networks:
      laravelnet:
        ipv4_address: ${APP_IP_ADDRESS}
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ${SOURCE_PATH}:/var/www/html/
      - ${PHP_LOG_PATH}:/var/log/php
    working_dir: /var/www/html/
    environment:
      TZ: ${TZ}
    tty: true

  # MySQL Container
  mysql:
    container_name: mysql
    hostname: mysql
    build:
      context: ./mysql/${USE_MYSQL_CONTAINER}
    networks:
      laravelnet:
        ipv4_address: ${MYSQL_IP_ADDRESS}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql/${USE_MYSQL_CONTAINER}/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/${USE_MYSQL_CONTAINER}/init:/docker-entrypoint-initdb.d/:ro
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: ${TZ}

# Network Config
networks:
  laravelnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/16
