version: '3.7'
services:
  # Web Container
  web:
    container_name: web
    hostname: web
    build:
      context: ./web
    privileged: true
    command: /sbin/init
    networks:
      laravelnet:
        ipv4_address: ${WEB_IP}
    ports:
      - 80:80
    volumes:
      - ${SOURCE_PATH}:/var/www/html/
      - ./web/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/php:/var/log/php
      - ./log/nginx:/var/log/nginx
    working_dir: /var/www/html/
    environment:
      TZ: ${TIMEZONE}
    tty: true

  # MySQL Container
  mysql:
    container_name: mysql
    hostname: mysql
    build:
      context: ./mysql/${USE_MYSQL_CONTAINER}
    networks:
      laravelnet:
        ipv4_address: ${MYSQL_IP_ADDRESS}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql/${USE_MYSQL_CONTAINER}/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/${USE_MYSQL_CONTAINER}/init:/docker-entrypoint-initdb.d/:ro
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: ${TIMEZONE}

# Network Config
networks:
  laravelnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.10.0/16
